---
title: "Data Manipulation"
author: "Alice Tivarovsky"
date: "9/19/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(janitor)
```


## load in a dataset

```{r}
litters_data = read_csv(file = "./data/FAS_litters.csv")
litters_data = janitor::clean_names((litters_data))

pups_data = read_csv(file = "./data/FAS_pups.csv")
pups_data = janitor::clean_names(pups_data)
```

## Selecting
### learning assessment 
```{r}
select (pups_data, litter_number, sex, pd_ears)
```


```{r}
select(litters_data, group, litter_number)
select(litters_data, group, litter_number, gd0_weight)
select(litters_data, litter_number, gd0_weight, starts_with("pups"))
select(litters_data, litter_number, group, gd0_weight)
select(litters_data, litter_number, group, everything())

select(litters_data, gd0_weight:pups_survive)
##renaming within select
select(litters_data, GROUP=group, litter_number)
```


## Filtering
### Learning assessment 
```{r}
filter(pups_data, sex == 1)
filter(pups_data, pd_walk < 11 & sex == 2)
```

```{r}
filter(litters_data, group=="Con7")

filter(litters_data, gd_of_birth ==20)

filter(litters_data, pups_born_alive < 6)

filter(litters_data, pups_born_alive < 6, group == "Con7")

```


## Mutate
### Learning assessment 
```{r}
mutate(pups_data,
        pd_minus_7 = pd_pivot - 7)

```

```{r}
mutate(litters_data, 
       wt_gain = gd18_weight - gd0_weight, 
       group = str_to_lower(group))
```


## Arrange

```{r}
```


## Piping

Create a collection of commands

### Learning assessment 
```{r}
pups_data = read_csv(file = "./data/FAS_pups.csv") %>% 
  janitor::clean_names() %>% 
  filter(sex == 1) %>% 
  select(-pd_ears) %>% 
  mutate(new_var = pd_pivot > 7)

```


